const express = require('express')
const router = express.Router()
const adminController = require('../../controllers/admin-controller')
const upload = require('../../middleware/multer')
router.get('/items/create', adminController.createItem)
router.get('/items/:id/edit', adminController.editItem)
router.put('/items/:id', upload.single('image'), adminController.putItem)
router.delete('/items/:id', adminController.deleteItem)
router.get('/items/:id', adminController.getItem)
router.post('/items', upload.single('image'), adminController.postItem)
router.get('/items', adminController.getItems)
router.use('/', (req, res) => res.redirect('/admin/items'))
module.exports = router
