const express = require('express')
const router = express.Router()
const adminController = require('../../controllers/admin-controller')
const categoryController = require('../../controllers/category-controller')
const upload = require('../../middleware/multer')
router.get('/items/create', adminController.createItem)
router.get('/items/:id/edit', adminController.editItem)
router.put('/items/:id', upload.single('image'), adminController.putItem)
router.delete('/items/:id', adminController.deleteItem)
router.get('/items/:id', adminController.getItem)
router.post('/items', upload.single('image'), adminController.postItem)
router.get('/items', adminController.getItems)
router.get('/users', adminController.getUsers)
router.patch('/users/:id', adminController.patchUser)
router.get('/categories/:id', categoryController.getCategories)
router.put('/categories/:id', categoryController.putCategory)
router.delete('/categories/:id', categoryController.deleteCategory)
router.get('/categories', categoryController.getCategories)
router.post('/categories', categoryController.postCategory)
router.use('/', (req, res) => res.redirect('/admin/items'))
module.exports = router
