const express = require('express')
const router = express.Router()
const passport = require('../config/passport')
const itemController = require('../controllers/item-controller')
const userController = require('../controllers/user-controller')
const commentController = require('../controllers/comment-controller')
const upload = require('../middleware/multer')
const { authenticated, authenticatedAdmin } = require('../middleware/auth')
const { generalErrorHandler } = require('../middleware/error-handler')
const admin = require('./modules/admin')
router.use('/admin', authenticatedAdmin, admin)
router.get('/signup', userController.signUpPage)
router.post('/signup', userController.signUp)
router.get('/signin', userController.signInPage)
router.post('/signin', passport.authenticate('local', { failureRedirect: '/signin', failureFlash: true }), userController.signIn)
router.get('/logout', userController.logout)
router.get('/items/:id/dashboard', itemController.getDashboard)
router.get('/items/feeds', authenticated, itemController.getFeeds)
router.get('/items/:id', authenticated, itemController.getItem)
router.get('/items', authenticated, itemController.getItems)
router.post('/comments', authenticated, commentController.postComment)
router.delete('/comments/:id', authenticatedAdmin, commentController.deleteComment)
router.get('/users/top', authenticated, userController.getTopUsers)
router.get('/users/:id', authenticated, userController.getUser)
router.get('/users/:id/edit', authenticated, userController.editUser)
router.put('/users/:id', authenticated, upload.single('image'), userController.putUser)
router.post('/favorite/:itemId', authenticated, userController.addFavorite)
router.delete('/favorite/:itemId', authenticated, userController.removeFavorite)
router.post('/following/:userId', authenticated, userController.addFollowing)
router.delete('/following/:userId', authenticated, userController.removeFollowing)
router.use('/', (req, res) => res.redirect('/items'))
router.use('/', generalErrorHandler)
module.exports = router
